### ISSUE TITLE
Crashes before extracting graphics packs

### ISSUE THREAD

**Issue by wonkieinc** [nosklo/cemu_utils#7]
2018-03-09 14:30:39,885: INFO upd_cemu(538) Initializing version beta2 (frozen)
2018-03-09 14:30:39,885: DEBUG upd_cemu(520) Command line: ['C:\\cemu_1.11.5\\upd_cemu.exe', 'C:\\Users\\fekwinten\\Desktop\\Breath of the Wild + CEMU 1.7.3 D\\The Legend of Zelda Breath of the Wild (1.33)\\code\\U-King.rpx']
2018-03-09 14:30:39,886: INFO upd_cemu(215) Reading config from 'C:\\cemu_1.11.5\\upd_cemu.json'
2018-03-09 14:30:39,886: DEBUG upd_cemu(553) Config: {'cemu_path': 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5', 'download_dir': 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5', 'delete_downloads': True, 'resolution_file': 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5\\res.txt', 'resolutions': set(), 'last_graphic_packs': 'graphicPacks_2-786.zip', 'last_cemuhook': None, 'keep_dir': 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5\\vault', 'gameid_list': set(), 'exec_cemu': True, 'extra_params': [], 'fullscreen': True, 'update_gameid_list': True, 'command_line_args': Namespace(config='C:\\cemu_1.11.5\\upd_cemu.json', game='C:\\Users\\fekwinten\\Desktop\\Breath of the Wild + CEMU 1.7.3 D\\The Legend of Zelda Breath of the Wild (1.33)\\code\\U-King.rpx', game_compat=None, mlc=None)}
2018-03-09 14:30:39,886: WARNING upd_cemu(397) Error reading resolutions from 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5\\res.txt'
2018-03-09 14:30:39,886: INFO upd_cemu(427) No change in resolutions.
2018-03-09 14:30:39,886: DEBUG upd_cemu(95) Searching for games in 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5\\mlc01'
2018-03-09 14:30:39,886: DEBUG upd_cemu(413) Games changed: set()
2018-03-09 14:30:39,887: DEBUG upd_cemu(72) Requesting last zip information from github...
2018-03-09 14:30:41,308: INFO upd_cemu(445) No change in repository download name
2018-03-09 14:30:41,308: INFO upd_cemu(83) Downloading 'https://github.com/slashiee/cemu_graphic_packs/releases/download/appveyor786/graphicPacks_2-786.zip'
2018-03-09 14:30:41,351: DEBUG selector_events(65) Using selector: SelectSelector
2018-03-09 14:30:43,612: ERROR upd_cemu(572) Fatal Error in main
Traceback (most recent call last):
  File "upd_cemu.py", line 555, in <module>
  File "upd_cemu.py", line 455, in detect_changes
  File "upd_cemu.py", line 449, in detect_changes_zip_pack
  File "upd_cemu.py", line 86, in download_pack
  File "upd_cemu.py", line 188, in urlretrieve
  File "asyncio\base_events.py", line 467, in run_until_complete
  File "upd_cemu.py", line 158, in _download
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fekwinten\\Desktop\\cemu_1.11.5\\graphicPacks_2-786.zip.incomplete'
2018-03-09 14:30:43,612: CRITICAL upd_cemu(573) Flushing log to file 'C:\\cemu_1.11.5\\upd_cemu_crashlog.txt'

**Comment by nosklo** [comment]
### Issue
Hi, looking from the log, it seems you changed cemu folder from 
`C:\Users\fekwinten\Desktop\cemu_1.11.5` to `C:\cemu_1.11.5` but copied the `upd_cemu.json` config file over, Then the tool is now looking for the files in the old path, that's why you get the error.

### FIX
To fix it, you can just delete your `upd_cemu.json` config file and it will be regenerated automatically with the new path.

**Comment by wonkieinc** [comment]
Oh, that makes sense, whoops. Thankyou!
